name: $(Year:yyyy).$(Month).$(DayOfMonth)$(Rev:.r)
resources:
  - repo: self
trigger:
  batch: true
  branches:
    include:
      - main
      - feature/*
      - bugfix/*
      - releases/*

variables:
  - template: templates/config.yml
stages:
  - stage: BuildNumber
    dependsOn: []
    displayName: Build
    jobs:
      - job: ChangeBranchName
        displayName: Change branch name
        pool:
          name: $(adoPool)
        steps:
          - powershell: |
              $BuildNumber="$(Build.BuildNumber)";
              $Branch = "$(Build.SourceBranchName)";
              $Configuration = "$(BuildConfiguration)";

                If (-Not ($Branch  -eq 'main'))
                {
                  $suffix = $Branch;

                  echo "##vso[build.updatebuildnumber]$($BuildNumber)-$($suffix)"
                }
            displayName: build number naming

  - stage: DEVDB
    displayName: DEV DB
    dependsOn: BuildNumber
    jobs:
      - template: templates/config-db.yml
        parameters:
          subscription: MetadentInternational
          subscriptionId: 9f3afebc-aa2c-42fa-97a3-7c9435c6721c
          dbKeyvaultConfigs:
            - dbAdminKeyvault: md-sql-afr-dev-01
              dbKeyvaults:
                - metadent-afr-be-dev-01
                - md-emails-dev-01
  - stage: PRDDB
    displayName: PRD DB
    dependsOn: DEVDB
    jobs:
      - template: templates/config-db.yml
        parameters:
          subscription: MetadentInternational
          subscriptionId: 9f3afebc-aa2c-42fa-97a3-7c9435c6721c
          dbKeyvaultConfigs:
            - dbAdminKeyvault: md-sql-afr-prd-01
              dbKeyvaults:
                - cal-be-prd-01
                - cal-emails-prd-01
                - crongen-be-prd-01
                - crongen-emails-prd-01
                - demo-be-prd-01
                - demo-emails-prd-01
                - idental-be-prd-01
                - idental-emails-prd-01
                - ffc-be-prd-01
                - ffc-emails-prd-01
                - mondzorg-be-prd-01
                - mondzorg-emails-prd-01
                - stg-i-be-prd-01
                - stg-i-emails-prd-01
                - stmary-be-prd-01
                - stmary-emails-prd-01
                - surgerytime-be-prd-02
                - surgerytime-emails-02
                - premium2-be-prd-01
                - premium2-emails-prd-01

  - stage: DEVStorageAccounts
    displayName: DEV Storage Accounts
    dependsOn: BuildNumber
    jobs:
      - template: templates/config-storage-accounts.yml
        parameters:
          subscription: MetadentInternational
          subscriptionId: 9f3afebc-aa2c-42fa-97a3-7c9435c6721c
          storageAccountKeyvaultConfigs:
            - storageAccountKeyvaults:
                - metadent-afr-be-dev-01

  - stage: PRDStorageAccounts
    displayName: PRD Storage Accounts
    dependsOn: DEVStorageAccounts
    jobs:
      - template: templates/config-storage-accounts.yml
        parameters:
          subscription: MetadentInternational
          subscriptionId: 9f3afebc-aa2c-42fa-97a3-7c9435c6721c
          storageAccountKeyvaultConfigs:
            - storageAccountKeyvaults:
                - cal-be-prd-01
                - crongen-be-prd-01
                - codeclinic-be-prd-01
                - demo-be-prd-01
                - idental-be-prd-01
                - ffc-be-prd-01
                - mondzorg-be-prd-01
                - stg-i-be-prd-01
                - stmary-be-prd-01
                - surgerytime-be-prd-02
                - premium2-be-prd-01

               

